import './globals.css'

export const metadata = {
  title: 'Supabase App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className="min-h-screen text-zinc-900 bg-white dark:bg-zinc-900 dark:text-zinc-100">
        {children}
      </body>
    </html>
  )
}
